### ISSUE TITLE
Correct email address in verification email

### ISSUE THREAD

**Issue by christinayung** [virusseq/keycloak-theme#2]
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/527fcc10-a50c-4847-8434-aa1d7d97fd77)

**Comment by lepsalex** [comment]
fixed in commit: [bd0068aec67399657c2bdb4ea8789dd538276ab8](https://github.com/cancogen-virus-seq/cancogen-keycloak-theme/commit/bd0068aec67399657c2bdb4ea8789dd538276ab8)
