### ISSUE TITLE
Support "forget password" when logging in

### ISSUE THREAD

**Issue by christinayung** [virusseq/keycloak-theme#3]

**Comment by christinayung** [comment]
Just tested this in prod. I got this message after clicking "Forgot Password"
![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/310a57ca-f048-44f9-a3eb-0b6c6a55444b)

But I didn't get the email.  Plus, I don't remember whether I actually created an account in Prod.

**Comment by rosibaj** [comment]
@christinayung You likely dont have an account on production yet. 

- I just used the forgot password and received the email to my inbox. 
- This is a keycloak feature how it is working [light docs here ](https://www.keycloak.org/docs/5.0/server_admin/#forgot-password)
- some consider it a security hole if you attempt to reset a password and it tells you if that user does/does not have an account 
- keycloak leans towards this, and gives the generic message you see there, but as you don't have an account you did not get an email. 
- based of documentation, im not sure if we can change the text in this alert.

**Comment by christinayung** [comment]
You're right. I confirmed that my email didn't have an account created. Interesting explanation. Got it and closing the ticket.
